name: Helm Chart Version Updater

on:
  pull_request:
    branches:
      - main

jobs:
  helm-chart-version-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.6.1
        with:
          since_last_remote_commit: 'true'
          files: |
            k8s/charts/events-hub-api/**
      - name: Extract branch name
        shell: bash
        run: |
          echo "branch=${{github.ref}}" >> $GITHUB_OUTPUT 
        id: extract_branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          path: main
          ref: main
      - name: Get version
        id: main
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "version=$(grep "version:" k8s/charts/events-hub-api/Chart.yaml | awk '{print $2}')\n" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
      - name: Check for chart file change
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Chart file was changed in this pull request"
          # install bumpversion
          sudo apt-get update
          sudo apt-get install -y bumpversion
          
          echo "${{ steps.extract_branch.outputs.branch }}"
          # update chart file version with bumpversion
          bumpversion patch --current-version ${{steps.main.outputs.version}} k8s/charts/events-hub-api/Chart.yaml --allow-dirty --verbose
          bumpversion patch --current-version ${{steps.main.outputs.version}} .cicd/deployment.yaml --allow-dirty --verbose      
          
          # commit chart files with new version
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add .
          # Commit changes and build files using new message
          git commit -m "chore(auto): Update helm chart version"
          # push to branch
          git push
        continue-on-error: true
      - name: End gracefully
        run: exit 1