name: Helm Chart Version Updater

on:
  pull_request:
    branches:
      - main

jobs:
  helm-chart-version-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.6.1
        with:
          since_last_remote_commit: 'true'
          files: |
            k8s/charts/events-hub-api/**
      - name: Check for chart file change
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Chart file was changed in this pull request"
          # install bumpversion
          sudo apt-get update
          sudo apt-get install -y bumpversion
          
       
          git checkout origin/main -- k8s/charts/events-hub-api/Chart.yaml
          current_version = $(grep "version:" k8s/charts/events-hub-api/Chart.yaml | awk '{print $2}')
          git restore
          bumpversion patch --current-version $current_version k8s/charts/events-hub-api/Chart.yaml --allow-dirty --verbose
          bumpversion patch --current-version $current_version .cicd/deployment.yaml --allow-dirty --verbose

          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add .
          # Commit changes and build files using same commit info as before
          git commit -m "chore(auto): Update helm chart version"
          # Force push to overwrite git history
          git push